#
# $Id: makefile.os3, 0.1, 2020/05/06 20:25:00, betajaen Exp $
#
# Parrot - Point and Click Adventure Game Player
# ==============================================
# 
# Copyright 2020 Robin Southern http://github.com/betajaen/parrot
# 
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.


# CONFIG

CC      = vc
CPU     = 68020
CFLAGS  = +aos68km -lamiga -nostdlib -IInclude -ITools/Squawk/Include -DPARROT_DEBUG

# PARROT

PARROT_OBJ = \
						start.o \
						log.o \
						graphics.o \
						ui.o \
						events.o \
						parrot_version.o \
						parrot_main.o

parrot: $(PARROT_OBJ) $(CONVERTER_MANIAC_OBJ) $(OPCODE_GENERATOR_OBJ)
	$(CC) $(CFLAGS) Parrot/minstart.o $(PARROT_OBJ) -o ../Releases/Parrot/Parrot

# OBJECTS

start.o: Parrot/Start.c
	$(CC) $(CFLAGS) -c Parrot/Start.c -o start.o
	
log.o: Parrot/Log.c
	$(CC) $(CFLAGS) -c Parrot/Log.c -o log.o
	
graphics.o: Parrot/Graphics.c
	$(CC) $(CFLAGS) -c Parrot/Graphics.c -o graphics.o
	
ui.o: Parrot/Ui.c
	$(CC) $(CFLAGS) -c Parrot/Ui.c -o ui.o
	
events.o: Parrot/Events.c
	$(CC) $(CFLAGS) -c Parrot/Events.c -o events.o

parrot_main.o: Parrot/Game/Main.c
	$(CC) $(CFLAGS) -c Parrot/Game/Main.c -o parrot_main.o

parrot_version.o: Parrot/Game/Version.c
	$(CC) $(CFLAGS) -c Parrot/Game/Version.c -o parrot_version.o

# CLEAN

.PHONY: clean

clean:
	rm ../Releases/Latest/Parrot
	rm ../Releases/Latest/Tools/ConvertManiac
	rm ../Releases/Latest/Tools/OpcodeGenerator
	rm $(PARROT_OBJ)

